### ISSUE TITLE
Set max-height in HTML template

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_related#14]
In the HTML template, it will not look nice, if the content is too long like the screenshot below.
Suggestion: 
maximize the height of the container. 

![screenshot_14](https://cloud.githubusercontent.com/assets/6613530/20522229/c39149d2-b0e1-11e6-8cd7-403900ac0c1a.jpg)

**Comment by acorbi** [comment]
@Huyeng this could be added as extra parameter to present when editors select **html** as template. We still need to implement the functionality to expose template-specific option fields on the widget.

**Comment by Huyeng** [comment]
Agreed with providing the further option for this. Anyways, it should set max-height as default for this template as well, but it can be customized on the widget.
