### ISSUE TITLE
The widget should be hidden when there is no related content

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_related#15]
![screenshot_18](https://cloud.githubusercontent.com/assets/6613530/20522693/3afb9e30-b0e4-11e6-89eb-d77c987086fd.jpg)

Test on page: https://pp.opendevelopmentcambodia.net/profiles/prey-lang-landscape/prey-land-protection/

**Comment by acorbi** [comment]
@Huyeng agreed! Assigning it to milestone 2.1.0
