### ISSUE TITLE
Split the related contents

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_related#2]
Currently, if more than one related content is added on a multi-language environment, many entries will be presented on the same box.

![screenshot from 2016-11-07 15-21-27](https://cloud.githubusercontent.com/assets/384894/20060975/01fdee5e-a4fe-11e6-9a5d-35065a5e9687.png)

It would be visually better to separate these and unify the delete function.

**Comment by Huyeng** [comment]
I tested several times, the pushed function for this is working fine with this issue even the deleted function. 
If any link is deleted either in English or Khmer, the links will be deleted from both container.   

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/20084459/11ca96c4-a595-11e6-85ca-b3cbd7bb8687.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/20084460/11f8f82a-a595-11e6-9f36-9821911b6bde.jpg)

**Deleting Function:
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/20084571/d7bc2eec-a595-11e6-8ea1-3a739cac283e.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/20084572/d7ecad38-a595-11e6-9fd4-bb655cb86e03.jpg)

**Comment by acorbi** [comment]
@Huyeng it is not working for me. Can you please check the actual code? I might have broken that functionality...

**Comment by Huyeng** [comment]
I tested on PP, the function is working as well. Would you mind to clear the catch and test again pls. 
You can have a look at the testing page below:
https://pp.opendevelopmentcambodia.net/wp-admin/post.php?post=96801&action=edit

**Comment by acorbi** [comment]
@Huyeng it works indeed for me as well on PP. closing
