### ISSUE TITLE
Warming: Related content

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_related#35]
Widget shows the error message if there is no related content added. 
![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/22049224/97da9406-dd64-11e6-8d68-2de090a1c399.jpg)

**Comment by acorbi** [comment]
@Huyeng can you pleaseALWAYS add a URL to the github Issues you raise? Otherwise I do not know where to go to see the issue

**Comment by Huyeng** [comment]
I'm sorry that I can't send you the URL. The error message appeared on the profile page of PROD site, then we take the widget always until it is fixed. 
I will add the widget on PP, and send you the URL.

**Comment by Huyeng** [comment]
It should happen on this page if the code hadn't been merged: 
https://pp.opendevelopmentcambodia.net/profiles/access-to-public-service/health-services-and-centers/

**Comment by acorbi** [comment]
Code has been merged and Issue seems to be fixed, right?
