### ISSUE TITLE
Invalid argument supplied for foreach() on backend

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_related#43]
The message below sometimes appeared when the post is published or updated.
Warning: Invalid argument supplied for foreach() in \wp-content\plugins\wp-odm_related\wp-odm_related.php on line 157

**Comment by acorbi** [comment]
fixed via 8e2791f55852ae571676be51f2955322b36ba98c

**Comment by Huyeng** [comment]
The error message is still appeared.
